In [38]:
from sklearn.svm import SVC
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn import datasets

In [39]:
df = datasets.load_iris(as_frame=True).frame

In [ ]:
df.head()
# df.isnull().sum()
# df.shaper

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm),target
0,5.1,3.5,1.4,0.2,0
1,4.9,3.0,1.4,0.2,0
2,4.7,3.2,1.3,0.2,0
3,4.6,3.1,1.5,0.2,0
4,5.0,3.6,1.4,0.2,0

In [41]:
x = df.drop("target",axis=1)
y = df["target"]

In [42]:
x.head()

   sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                5.1               3.5                1.4               0.2
1                4.9               3.0                1.4               0.2
2                4.7               3.2                1.3               0.2
3                4.6               3.1                1.5               0.2
4                5.0               3.6                1.4               0.2

In [43]:
x_train , x_test , y_train , y_test = train_test_split(
    x,y, test_size=0.3 , random_state = 42
)

In [44]:
x_train.head()

     sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
81                 5.5               2.4                3.7               1.0
133                6.3               2.8                5.1               1.5
137                6.4               3.1                5.5               1.8
75                 6.6               3.0                4.4               1.4
109                7.2               3.6                6.1               2.5

In [45]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

x_train_scaled = scaler.fit_transform(x_train)
x_test_scaled  = scaler.transform(x_test)

In [46]:
x_train_scaled

array([[-0.4134164 , -1.46200287, -0.09951105, -0.32339776],
       [ 0.55122187, -0.50256349,  0.71770262,  0.35303182],
       [ 0.67180165,  0.21701605,  0.95119225,  0.75888956],
       [ 0.91296121, -0.02284379,  0.30909579,  0.2177459 ],
       [ 1.63643991,  1.41631528,  1.30142668,  1.70589097],
       [-0.17225683, -0.26270364,  0.19235097,  0.08245999],
       [ 2.11875905, -0.02284379,  1.59328871,  1.16474731],
       [-0.29283662, -0.02284379,  0.36746819,  0.35303182],
       [-0.89573553,  1.17645543, -1.44207638, -1.40568508],
       [ 2.23933883, -0.50256349,  1.65166111,  1.0294614 ],
       [-0.05167705, -0.74242333,  0.13397857, -0.32339776],
       [-0.77515575,  0.93659559, -1.44207638, -1.40568508],
       [-1.01631531,  1.17645543, -1.50044878, -1.27039917],
       [-0.89573553,  1.89603497, -1.15021435, -1.13511325],
       [-1.01631531, -2.42144225, -0.21625586, -0.32339776],
       [ 0.55122187, -0.74242333,  0.60095781,  0.75888956],
       [-1.25747488,  0.93659559, -1.15021435, -1.40568508],
       [-1.01631531, -0.02284379, -1.32533157, -1.40568508],
       [-0.89573553,  0.69673574, -1.26695916, -0.99982734],
       [-0.29283662, -0.74242333,  0.19235097,  0.08245999],
       [-0.89573553,  0.93659559, -1.38370397, -1.40568508],
       [-0.17225683, -0.02284379,  0.19235097, -0.05282593],
       [ 2.23933883,  1.89603497,  1.65166111,  1.30003323],
       [-1.49863445,  0.4568759 , -1.44207638, -1.40568508],
       [ 0.43064208, -0.26270364,  0.25072338,  0.08245999],
       [-0.17225683, -1.22214302,  0.65933022,  1.0294614 ],
       [-0.4134164 ,  2.85547435, -1.44207638, -1.40568508],
       [ 0.18948252, -0.02284379,  0.54258541,  0.75888956],
       [-0.05167705, -0.74242333,  0.71770262,  0.89417548],
       [ 0.18948252, -1.94172256,  0.07560616, -0.32339776],
       [-0.53399618, -0.02284379,  0.36746819,  0.35303182],
       [ 0.43064208,  0.93659559,  0.89281984,  1.43531914],
       [-0.4134164 , -1.70186271,  0.07560616,  0.08245999],
       [-0.53399618,  2.13589481, -1.26695916, -1.13511325],
       [-1.01631531, -1.70186271, -0.33300068, -0.32339776],
       [ 0.67180165, -0.74242333,  0.83444743,  0.89417548],
       [-1.01631531,  0.69673574, -1.44207638, -1.40568508],
       [-1.01631531,  0.4568759 , -1.55882119, -1.40568508],
       [-0.4134164 , -1.46200287, -0.04113865, -0.18811184],
       [ 1.033541  , -0.02284379,  0.65933022,  0.62360365],
       [-1.1368951 ,  0.21701605, -1.38370397, -1.40568508],
       [-0.05167705, -0.50256349,  0.71770262,  1.57060506],
       [-1.01631531,  0.93659559, -1.38370397, -1.40568508],
       [-1.01631531,  1.17645543, -1.32533157, -0.86454142],
       [ 0.06890273,  0.4568759 ,  0.54258541,  0.75888956],
       [-0.89573553, -1.22214302, -0.50811789, -0.18811184],
       [ 1.27470056,  0.4568759 ,  1.06793706,  1.43531914],
       [ 0.18948252, -0.74242333,  0.71770262,  0.48831773],
       [ 0.3100623 , -0.98228318,  1.00956465,  0.2177459 ],
       [ 2.23933883, -0.02284379,  1.30142668,  1.43531914],
       [-0.4134164 , -1.22214302,  0.07560616,  0.08245999],
       [-1.73979401, -0.26270364, -1.44207638, -1.40568508],
       [-1.8603738 , -0.02284379, -1.6171936 , -1.540971  ],
       [ 0.18948252, -1.94172256,  0.65933022,  0.35303182],
       [ 1.63643991,  0.4568759 ,  1.24305427,  0.75888956],
       [-1.49863445,  0.21701605, -1.38370397, -1.40568508],
       [-0.89573553,  1.17645543, -1.44207638, -1.27039917],
       [-1.73979401, -0.02284379, -1.50044878, -1.40568508],
       [ 0.55122187, -1.22214302,  0.60095781,  0.35303182],
       [ 0.55122187,  0.93659559,  1.00956465,  1.57060506],
       [-1.49863445,  0.93659559, -1.44207638, -1.27039917],
       [ 1.15412078, -0.02284379,  0.95119225,  1.16474731],
       [ 0.55122187,  0.69673574,  1.24305427,  1.70589097],
       [-1.37805466,  0.4568759 , -1.50044878, -1.40568508],
       [ 0.3100623 , -0.26270364,  0.484213  ,  0.2177459 ],
       [ 0.79238143, -0.50256349,  0.4258406 ,  0.35303182],
       [ 0.43064208, -0.50256349,  0.54258541,  0.75888956],
       [ 1.39528035,  0.4568759 ,  0.484213  ,  0.2177459 ],
       [ 0.67180165,  0.4568759 ,  0.83444743,  1.43531914],
       [-0.89573553,  1.89603497, -1.32533157, -1.40568508],
       [ 1.27470056,  0.21701605,  0.89281984,  1.16474731],
       [ 0.06890273, -0.02284379,  0.19235097,  0.35303182],
       [ 0.79238143, -0.02284379,  0.77607503,  1.0294614 ],
       [-0.17225683, -0.98228318, -0.21625586, -0.32339776],
       [-0.77515575, -0.74242333,  0.01723376,  0.2177459 ],
       [ 0.3100623 , -0.02284379,  0.4258406 ,  0.2177459 ],
       [-1.61921423, -1.70186271, -1.50044878, -1.27039917],
       [ 0.91296121, -0.26270364,  0.4258406 ,  0.08245999],
       [-0.4134164 , -0.98228318,  0.30909579, -0.05282593],
       [-0.65457597,  1.65617512, -1.38370397, -1.40568508],
       [-0.29283662, -0.02284379,  0.13397857,  0.08245999],
       [ 1.7570197 , -0.26270364,  1.41817149,  0.75888956],
       [ 1.033541  ,  0.69673574,  1.06793706,  1.16474731],
       [-0.89573553,  1.65617512, -1.38370397, -1.13511325],
       [-1.1368951 , -1.46200287, -0.33300068, -0.32339776],
       [ 1.033541  ,  0.69673574,  1.06793706,  1.70589097],
       [ 1.63643991, -0.02284379,  1.12630946,  0.48831773],
       [-1.1368951 ,  1.41631528, -1.44207638, -1.540971  ],
       [ 1.033541  ,  0.21701605,  1.00956465,  1.57060506],
       [-1.1368951 , -0.02284379, -1.44207638, -1.40568508],
       [ 1.27470056,  0.21701605,  0.60095781,  0.35303182],
       [ 1.87759948, -0.50256349,  1.30142668,  0.89417548],
       [ 0.55122187, -0.26270364,  1.00956465,  0.75888956],
       [-0.17225683, -0.50256349,  0.13397857,  0.08245999],
       [ 0.79238143, -0.02284379,  0.95119225,  0.75888956],
       [ 0.55122187, -1.70186271,  0.30909579,  0.08245999],
       [ 0.67180165, -0.26270364,  0.25072338,  0.08245999],
       [-0.29283662, -0.50256349,  0.60095781,  1.0294614 ],
       [ 0.06890273, -0.02284379,  0.71770262,  0.75888956],
       [-0.53399618,  0.93659559, -1.26695916, -1.40568508],
       [ 0.3100623 , -0.50256349,  0.07560616,  0.08245999],
       [-1.1368951 , -1.22214302,  0.36746819,  0.62360365],
       [-0.05167705,  2.37575466, -1.55882119, -1.40568508],
       [-0.05167705, -0.98228318,  0.07560616, -0.05282593],
       [ 1.51586013, -0.02284379,  1.18468187,  1.16474731]])

In [55]:

svc = SVC()
svc.fit(x_train_scaled, y_train)

SVC()

In [56]:
y_pred = svc.predict(x_test_scaled)

In [57]:
# Evaluate

from sklearn.metrics import accuracy_score , classification_report

print("\naccuracy_score\n:",accuracy_score(y_test,y_pred)),
print("\nclassification_report\n:",classification_report(y_test,y_pred))

accuracy_score
: 1.0

classification_report
:               precision    recall  f1-score   support

           0       1.00      1.00      1.00        19
           1       1.00      1.00      1.00        13
           2       1.00      1.00      1.00        13

    accuracy                           1.00        45
   macro avg       1.00      1.00      1.00        45
weighted avg       1.00      1.00      1.00        45

In [58]:
# Linear Kernel

svc = SVC(kernel="linear")
svc.fit(x_train_scaled,y_train)
y_pred = svc.predict(x_test_scaled)
print("accuracy_score :",accuracy_score(y_test,y_pred))

accuracy_score : 0.9777777777777777

In [ ]:
from sklearn.svm import SVC

# Polynomial Kernel
svc = SVC(kernel="poly")
svc.fit(x_train_scaled, y_train)

y_pred = svc.predict(x_test_scaled)
print("accuracy_score :",accuracy_score(y_test,y_pred))

accuracy_score : 0.9555555555555556

In [66]:
#sigmed

c_vals = [0.5,1,2,3,4,5]

for c_vals in c_vals:
    svc = SVC(C=c_vals, kernel="rbf")
    svc.fit(x_train_scaled,y_train)

    y_pred = svc.predict(x_test_scaled)
    print("c =",c_vals,"& accuracy :",accuracy_score(y_test,y_pred))

c = 0.5 & accuracy : 1.0
c = 1 & accuracy : 1.0
c = 2 & accuracy : 1.0
c = 3 & accuracy : 1.0
c = 4 & accuracy : 1.0
c = 5 & accuracy : 1.0